#!/bin/bash

#set -eo pipefail


if [ "$#" -lt 1 ]
then
 echo "usage: sudo $0 <csv>"
 exit 0
fi

execpath=`dirname $0`
execpath=`realpath $execpath`


csv=$1
ssh_key=~/.ssh/id_rsa #YOU NEED TO UPDATE THIS

linenum=1
for user in `cat $csv  | awk -F, '{print $1}'`
do

 remote_path=`cat $csv | head -n $linenum | tail -n 1 |  awk -F, '{print $2}'`
 writable=`cat $csv | head -n $linenum | tail -n 1 |  awk -F, '{print $3}'`

 
 echo $user
 echo $remote_path
 echo "writable: $writable"

 if [ "$writable" = "1" ]
 then
	echo "$remote_path is writable"
else
	writable=0
fi

 id $user &> /dev/null
 if [[ $? == 0 ]]
 then
	 echo "Mounting share for $user"
	 $execpath/sftp_mount_sshfs $user $remote_path $ssh_key $writable
 else
	 echo "User $user does not exist!"
	 continue
 fi

 linenum=$((linenum+1)) 
done

